title: Portafolio de Nikolas Quintano
author: Nikolas Quintano
email: nicolas.quintano@opendeusto.es
description: > # this means to ignore newlines until "baseurl:"
  Bienvenido a mi portafolio. ¡Disfruta!

# social links
twitter_username: nikolasquintano # NO incluyas el carácter @ character, ¡o la compilación fallará!
github_username:  NikolasQuintano # NO incluyas el carácter @ character, ¡o la compilación fallará!

show_excerpts: true # cámbialo a false para eliminar los extractos de la página principal

theme: minima